// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void chromeSearch() {
    System.setProperty("webdriver.chrome.driver","src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://subscribe.ru/");
    driver.findElement(By.xpath("//*[@id=\"all\"]/header/ul/li[2]/a")).click();
    driver.findElement(By.xpath("//*[@id=\"all\"]/header/div[3]/form/div/input")).sendKeys("qwerty");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".search-submit")).click();
    vars.put("win7363", waitForWindow(2000));
    Exception exception = assertThrows(RuntimeException.class, () -> {
      driver.findElement(By.xpath("//*[@id=\"p404\"]/div[1]/h1"));
    });
    assertTrue(exception != null);
  }

  @Test
  public void firefoxSearch() {
    System.setProperty("webdriver.gecko.driver","src\\main\\resources\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://subscribe.ru/");
    driver.findElement(By.xpath("//*[@id=\"all\"]/header/ul/li[2]/a")).click();
    driver.findElement(By.xpath("//*[@id=\"all\"]/header/div[3]/form/div/input")).sendKeys("qwerty");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".search-submit")).click();
    vars.put("win7363", waitForWindow(2000));
    Exception exception = assertThrows(RuntimeException.class, () -> {
      driver.findElement(By.xpath("//*[@id=\"p404\"]/div[1]/h1"));
    });
    assertTrue(exception != null);
  }
}
